# Generated by Django 3.2.9 on 2021-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'Disponibilidad departamento'], [1, 'Cancelar reserva'], [2, 'Más información departamentos'], [3, 'Dudas'], [4, 'Quejas y/o reclamos']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=20)),
                ('repContrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('fechaArriendo', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('acompanantes', models.IntegerField()),
                ('departamento', models.IntegerField(choices=[[0, 'Departamento 1'], [1, 'Departamento 2'], [2, 'Departamento 3']])),
                ('servicioExtra', models.IntegerField(choices=[[0, 'Transporte'], [1, 'Cama extra'], [2, 'Televisor extra'], [3, 'Cocina eléctrica']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
