# Generated by Django 3.2.9 on 2021-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismoReal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='contrasena',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='contrasena',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='repContrasena',
            new_name='repetir_contraseña',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaArriendo',
            new_name='fecha_arriendo',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fechaTermino',
            new_name='fecha_termino',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='servicioExtra',
            new_name='servicio_extra',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
