# Generated by Django 3.2.9 on 2021-11-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismoReal', '0002_auto_20211128_0405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
