# Generated by Django 3.2.9 on 2021-11-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismoReal', '0003_auto_20211128_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='departamento',
            field=models.IntegerField(choices=[[0, 'Departamento 1, $300.000'], [1, 'Departamento 2, $400.000'], [2, 'Departamento 3, $550.000']]),
        ),
    ]
