# Generated by Django 3.2.9 on 2021-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismoReal', '0004_alter_reserva_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_de_pago',
            field=models.IntegerField(choices=[[0, 'Tarjeta de crédito'], [1, 'Tarjeta de débito'], [2, 'Paypal']], default=1),
            preserve_default=False,
        ),
    ]
